version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: shopwise
      POSTGRES_PASSWORD: shopwise123
      POSTGRES_DB: shopwise
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./backend/ShopWise.Api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Host=db;Database=shopwise;Username=shopwise;Password=shopwise123"
      Jwt__Key: "superSecretKeyThatShouldBeInVaultNotHere"
      Jwt__Issuer: "ShopWise"
      Jwt__Audience: "ShopWise"
      Gemini__ApiKey: "${GEMINI_API_KEY:-}"
    ports:
      - "5100:8080"
    volumes:
      - ./backend/ShopWise.Api/wwwroot/images:/app/wwwroot/images
    depends_on:
      - db

  frontend:
    build: ./frontend/shopwise-ui
    restart: unless-stopped
    ports:
      - "3000:5173"
    volumes:
      - ./frontend/shopwise-ui:/app
      - /app/node_modules
    depends_on:
      - api

  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    command: sleep infinity
    depends_on:
      - db
      - api
      - frontend

volumes:
  postgres_data:
